---
# Ignored, since newer distros don't need this package
# https://github.com/jnv/ansible-role-unattended-upgrades/issues/6
- name: "Install update-notifier-common"
  ansible.builtin.apt:
    pkg: "update-notifier-common"
    state: "present"
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  failed_when: false
